"""
Groq AI Analyzer Service
Integrates ultra-fast LLMs via Groq Cloud API (llama-3.3-70b-versatile and llama-3.1-8b-instant)
to provide intelligent market sentiment, trade reasoning analysis, and confidence scoring.
"""

import json
import logging
import os
import re
from typing import Dict, Optional, Any, List
from dataclasses import dataclass
import requests

from services.data_guard import DataGuard, DATA_UNAVAILABLE

logger = logging.getLogger(__name__)


# List of valid, active Groq fallback models for automatic failover
GROQ_FALLBACK_MODELS = [
    "qwen/qwen3.6-27b",
    "groq/compound",
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "llama-3.2-3b-preview",
    "llama3-70b-8192",
]


@dataclass
class AIAnalysisResult:
    """Represents the structured analysis generated by Groq AI."""
    summary: str
    sentiment: str  # BULLISH, BEARISH, NEUTRAL
    confidence_score: int  # 0 - 100
    catalysts: str
    model_used: Optional[str] = None
    raw_response: Optional[str] = None


def format_for_telegram_html(text: str) -> str:
    """
    Converts markdown formatting (**bold**, *italic*, `code`, [links]) to clean Telegram HTML tags
    (<b>, <i>, <code>, <pre>) and escapes unsupported tags or brackets safely.
    """
    if not text:
        return ""

    # Convert code blocks ```code``` to <pre><code>...</code></pre>
    formatted = re.sub(r'```(\w+)?\n?(.*?)```', r'<pre><code>\2</code></pre>', text, flags=re.DOTALL)
    # Convert inline code `text` to <code>text</code>
    formatted = re.sub(r'`([^`\n]+)`', r'<code>\1</code>', formatted)
    # Convert bold **text** or __text__ to <b>text</b>
    formatted = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', formatted)
    formatted = re.sub(r'__(.+?)__', r'<b>\1</b>', formatted)
    # Convert italic *text* or _text_ to <i>text</i> (without breaking tags)
    formatted = re.sub(r'(?<![<a-zA-Z0-9])\*([^*]+?)\*(?![a-zA-Z0-9>])', r'<i>\1</i>', formatted)
    formatted = re.sub(r'(?<![<a-zA-Z0-9])_([^_]+?)_(?![a-zA-Z0-9>])', r'<i>\1</i>', formatted)
    # Convert markdown links [title](url) to title (url) or bold title
    formatted = re.sub(r'\[([^\]]+)\]\((https?://[^\)]+)\)', r'<a href="\2">\1</a>', formatted)
    # Sanitize any stray brackets used as placeholders (e.g. [kaut kādu tēmu]) by escaping if needed
    formatted = re.sub(r'<(?!\/?(?:b|i|code|pre|a|em|strong|u|s|strike|del)(?: [^>]*)?>)', '&lt;', formatted)

    return formatted.strip()


class GroqClient:
    """
    Client for Groq Cloud AI API.
    Interacts with ultra-fast LLMs via OpenAI-compatible chat completions endpoint:
    https://api.groq.com/openai/v1/chat/completions
    """

    ENDPOINT_URL = "https://api.groq.com/openai/v1/chat/completions"
    MODELS_URL = "https://api.groq.com/openai/v1/models"

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        model_name: Optional[str] = None,
        fallback_models: Optional[List[str]] = None,
        timeout: int = 20,
        openrouter_api_key: Optional[str] = None,
        openrouter_model: Optional[str] = None,
        **kwargs: Any
    ):
        raw_key = (
            api_key
            or openrouter_api_key
            or os.getenv("GROQ_API_KEY")
            or os.getenv("OPENROUTER_API_KEY")
            or ""
        )
        raw_model = (
            model
            or model_name
            or openrouter_model
            or os.getenv("GROQ_MODEL")
            or os.getenv("OPENROUTER_MODEL")
            or "qwen/qwen3.6-27b"
        )
        self.api_key = raw_key.strip()
        self.model = raw_model.strip()
        self.fallback_models = fallback_models or GROQ_FALLBACK_MODELS
        self.timeout = timeout
        self.url = self.ENDPOINT_URL.strip()
        self.models_url = self.MODELS_URL.strip()
        self._dynamic_models: Optional[List[str]] = None

        self._session = requests.Session()
        # Query active models dynamically on initialization
        if self.is_configured():
            try:
                self._fetch_available_models()
            except Exception:
                pass

    def _get_headers(self) -> Dict[str, str]:
        """
        Builds the required request headers for Groq API.
        Includes Authorization Bearer token.
        """
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "TBOT-Trading-Bot/1.0",
        }
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        return headers

    def is_configured(self) -> bool:
        """Checks if a valid Groq API key is configured."""
        return bool(
            self.api_key
            and self.api_key not in ("your_groq_api_key_here", "your_openrouter_api_key_here", "")
        )

    def _fetch_available_models(self) -> List[str]:
        """
        Queries the Groq models endpoint dynamically to detect currently active model IDs.
        Filters for text/chat models and logs the available models for the active key.
        """
        if self._dynamic_models is not None:
            return self._dynamic_models

        if not self.is_configured():
            self._dynamic_models = list(self.fallback_models)
            return self._dynamic_models

        try:
            try:
                resp = self._session.get(self.models_url, headers=self._get_headers(), timeout=5)
            except requests.exceptions.SSLError:
                resp = self._session.get(self.models_url, headers=self._get_headers(), timeout=5, verify=False)

            if resp.status_code == 200:
                data = resp.json()
                model_entries = data.get("data", [])
                active_ids: List[str] = []
                for entry in model_entries:
                    m_id = entry.get("id", "").strip()
                    # Filter out audio/whisper/embedding/guard models
                    if m_id and not any(ex in m_id.lower() for ex in ("whisper", "tts", "embedding", "guard", "moderation")):
                        if entry.get("active", True):
                            active_ids.append(m_id)

                if active_ids:
                    self._dynamic_models = active_ids
                    logger.info(f"Available Groq models discovered: {self._dynamic_models}")
                    return self._dynamic_models
            else:
                logger.warning(f"Groq models discovery returned HTTP {resp.status_code}. Using default fallbacks.")
        except Exception as e:
            logger.debug(f"Dynamic Groq model resolution notice ({e}). Using default fallbacks.")

        self._dynamic_models = list(self.fallback_models)
        logger.info(f"Using default Groq candidate models: {self._dynamic_models}")
        return self._dynamic_models

    def _extract_json_from_text(self, text: str) -> Dict[str, Any]:
        """Extracts JSON object from model response text safely."""
        text = text.strip()
        # Strip markdown code fences if present
        if "```" in text:
            match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
            if match:
                return json.loads(match.group(1))
            text = text.strip("`")
            if text.startswith("json"):
                text = text[4:].strip()

        # Try finding the first outermost JSON object
        json_match = re.search(r"(\{.*\})", text, re.DOTALL)
        if json_match:
            return json.loads(json_match.group(1))

        return json.loads(text)

    def _get_model_candidate_list(self) -> List[str]:
        """Returns the primary model followed by dynamic and fallback models in unique order."""
        dynamic = self._fetch_available_models()
        candidates = [self.model]
        for m in dynamic:
            if m and m not in candidates:
                candidates.append(m)
        for fb in self.fallback_models:
            if fb and fb not in candidates:
                candidates.append(fb)
        return candidates

    def _post_request(self, payload: Dict[str, Any]) -> requests.Response:
        """Sends HTTP POST to Groq API with automatic SSL certificate fallback."""
        try:
            return self._session.post(
                self.url,
                json=payload,
                headers=self._get_headers(),
                timeout=self.timeout
            )
        except requests.exceptions.SSLError:
            logger.warning("SSLError encountered connecting to Groq. Retrying with verify=False fallback.")
            return self._session.post(
                self.url,
                json=payload,
                headers=self._get_headers(),
                timeout=self.timeout,
                verify=False
            )

    def analyze_trade_signal(
        self,
        ticker: str,
        price: float,
        action: str,
        reason: str,
        indicators: Dict[str, Any],
        historical_stats: Optional[Dict[str, Any]] = None,
        historical_lessons: Optional[List[str]] = None
    ) -> AIAnalysisResult:
        """
        Analyzes a candidate trade signal using Groq AI with automatic fallback model routing,
        strict DataGuard sanitization to prevent hallucinations, and historical ML track record & autopsy memory context.
        """
        if not self.is_configured():
            logger.info("Groq API key not configured. Returning default rule-based analysis.")
            return AIAnalysisResult(
                summary=f"Technical Rule Trigger: {reason}",
                sentiment="BULLISH" if action.upper() == "BUY" else "BEARISH",
                confidence_score=75,
                catalysts="Technical indicator threshold reached.",
                model_used="rule-engine-fallback"
            )

        # Sanitize all market metrics via DataGuard
        clean_indicators = DataGuard.sanitize_indicators(indicators)
        clean_price_str = f"${price:,.2f}" if price and price > 0 else DATA_UNAVAILABLE

        # Build historical feedback string if stats/lessons are present
        stats_context = ""
        if historical_stats and historical_stats.get("evaluated_count", 0) > 0:
            win_rate = historical_stats.get("win_rate_percent", 0.0)
            eval_count = historical_stats.get("evaluated_count", 0)
            avg_pnl = historical_stats.get("avg_pnl_percent", 0.0)
            stats_context += f"\n- Historical Strategy Performance: {win_rate}% Win Rate across {eval_count} past forward-tested signals (Avg PnL: {avg_pnl:+.2f}%)."
            stats_context += "\n- Learning Directive: Scrutinize whether market conditions match past successful dip-reversals versus fakeouts."

        if historical_lessons:
            stats_context += "\n- Retrospective Lessons from Past Trade Autopsies:\n"
            for lesson in historical_lessons[:4]:
                stats_context += f"  • {lesson}\n"

        prompt_text = f"""
You are an expert quantitative and financial market analyst AI assistant.
Analyze this proposed trade execution hypothesis:

- Ticker: {ticker}
- Action: {action.upper()}
- Validated Price: {clean_price_str}
- Trigger Reason: {reason}
- Technical Metrics (DataGuard Sanitized): {json.dumps(clean_indicators, default=str)}
{stats_context}
CRITICAL ANTI-HALLUCINATION DIRECTIVE:
Any metric marked as 'DATA_UNAVAILABLE' is missing from the data provider and must NEVER be guessed, estimated, or hallucinated. Base your analysis solely on the verified values provided.

Respond with a valid JSON object strictly matching this schema:
{{
  "sentiment": "BULLISH" or "BEARISH" or "NEUTRAL",
  "confidence_score": 0-100,
  "summary": "1-2 concise sentences summarizing the risk/reward rationale",
  "catalysts": "Key technical or momentum catalyst"
}}
"""

        candidate_models = self._get_model_candidate_list()
        last_error_msg = ""

        for idx, current_model in enumerate(candidate_models):
            payload = {
                "model": current_model,
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a professional financial trading analyst. Always respond with raw valid JSON only."
                    },
                    {
                        "role": "user",
                        "content": prompt_text
                    }
                ],
                "temperature": 0.2
            }

            try:
                logger.info(
                    f"Requesting AI trade analysis from Groq [{current_model}] "
                    f"(Candidate {idx + 1}/{len(candidate_models)}) for {ticker}..."
                )
                response = self._post_request(payload)

                if response.status_code in (400, 404, 422, 429, 500, 502, 503, 504):
                    logger.warning(
                        f"Groq model '{current_model}' returned HTTP {response.status_code}: {response.text[:150]}. "
                        f"Attempting next fallback model..."
                    )
                    last_error_msg = f"HTTP {response.status_code}: {response.text}"
                    continue

                if not response.ok:
                    logger.error(
                        f"Groq API request failed with status {response.status_code} on {self.url}: {response.text}"
                    )
                    last_error_msg = f"HTTP {response.status_code}: {response.text}"
                    continue

                data = response.json()
                choices = data.get("choices", [])
                if not choices:
                    logger.warning(f"No choices returned by model '{current_model}'. Trying next fallback...")
                    last_error_msg = f"Empty choices response from {current_model}"
                    continue

                content = choices[0].get("message", {}).get("content", "").strip()

                try:
                    parsed = self._extract_json_from_text(content)
                    sentiment = str(parsed.get("sentiment", "NEUTRAL")).upper()
                    confidence = int(parsed.get("confidence_score", 70))
                    summary = str(parsed.get("summary", reason))
                    catalysts = str(parsed.get("catalysts", "Technical trigger"))
                except Exception as parse_err:
                    logger.warning(f"Could not parse JSON from Groq output ({parse_err}). Raw: {content}")
                    sentiment = "BULLISH" if action.upper() == "BUY" else "BEARISH"
                    confidence = 70
                    summary = content if len(content) < 200 else reason
                    catalysts = "Technical rule"

                logger.info(f"AI analysis successfully generated using Groq model [{current_model}].")
                return AIAnalysisResult(
                    summary=summary,
                    sentiment=sentiment,
                    confidence_score=confidence,
                    catalysts=catalysts,
                    model_used=current_model,
                    raw_response=content
                )

            except Exception as e:
                logger.warning(f"Request failed for Groq model '{current_model}': {e}.")
                last_error_msg = str(e)
                continue

        # If all candidate models failed
        logger.warning(
            f"All Groq models failed ({candidate_models}). Last error: {last_error_msg}. Reverting to rule-based analysis."
        )
        return AIAnalysisResult(
            summary=f"Technical Rule Trigger: {reason}",
            sentiment="BULLISH" if action.upper() == "BUY" else "BEARISH",
            confidence_score=70,
            catalysts="Technical indicator threshold.",
            model_used="rule-engine-fallback",
            raw_response=last_error_msg
        )

    def generate_chat_response(
        self,
        messages: List[Dict[str, str]],
        temperature: float = 0.3,
        max_tokens: int = 300
    ) -> str:
        """
        Sends a multi-turn or contextual chat prompt to Groq LLM and returns concise formatted response text.
        Seamlessly falls back across candidate models on 404, 400, 429, or 5xx errors.
        """
        if not self.is_configured():
            return "🤖 Groq Cloud AI API key is not configured. Please add GROQ_API_KEY in .env."

        candidate_models = self._get_model_candidate_list()
        last_error_msg = "Unknown error"

        for current_model in candidate_models:
            payload = {
                "model": current_model,
                "messages": messages,
                "temperature": temperature,
                "max_tokens": max_tokens
            }
            try:
                response = self._post_request(payload)
                if response.status_code in (400, 404, 422, 429, 500, 502, 503, 504):
                    logger.warning(
                        f"Groq chat model '{current_model}' returned HTTP {response.status_code}. "
                        f"Attempting next fallback model..."
                    )
                    last_error_msg = f"HTTP {response.status_code}: {response.text}"
                    continue

                if response.ok:
                    data = response.json()
                    choices = data.get("choices", [])
                    if choices:
                        raw_content = choices[0].get("message", {}).get("content", "").strip()
                        # Deduplicate pathological repeated sentences / token loop glitch
                        lines = raw_content.splitlines()
                        deduped_lines = []
                        prev_line = ""
                        repeat_count = 0
                        for line in lines:
                            line_stripped = line.strip()
                            if line_stripped and line_stripped == prev_line:
                                repeat_count += 1
                                if repeat_count >= 2:
                                    continue
                            else:
                                repeat_count = 0
                                prev_line = line_stripped
                            deduped_lines.append(line)
                        cleaned_content = "\n".join(deduped_lines).strip()
                        return format_for_telegram_html(cleaned_content)
                else:
                    last_error_msg = f"HTTP {response.status_code}: {response.text}"
            except Exception as e:
                logger.debug(f"Groq query failed for {current_model}: {e}")
                last_error_msg = str(e)
                continue

        logger.warning(f"All Groq models failed ({candidate_models}). Last error: {last_error_msg}")
        return f"⚠️ Groq AI models currently unavailable ({last_error_msg})."

    def answer_market_query(
        self,
        question: str,
        portfolio_context: Optional[Dict[str, Any]] = None,
        radar_context: Optional[List[Dict[str, Any]]] = None,
        recent_lessons: Optional[List[str]] = None,
        log_context: Optional[str] = None,
        regime_context: Optional[str] = None,
        trade_history_context: Optional[str] = None,
        universe_context: Optional[str] = None,
        obsidian_context: Optional[str] = None
    ) -> str:
        """
        Universal natural language AI consultation with KODA Trading Intelligence OS.
        Communicates in natural, fluent Latvian as an elite quantitative trading partner,
        grounded in live portfolio metrics, market regime, trade autopsies, system logs,
        universe asset coverage, Obsidian vault sync, and executed trade history.
        """
        if not self.is_configured():
            return "🤖 Groq Cloud AI API key is not configured. Please add GROQ_API_KEY in .env."

        # Format compact context blocks
        context_parts = []
        if regime_context:
            context_parts.append(f"Tirgus režīms: {regime_context}")
        if portfolio_context:
            context_parts.append(
                f"Portfelis: Akcijas=${portfolio_context.get('stock_free', 0):,.0f}, Kripto={portfolio_context.get('crypto_free', 0):,.0f} USDT, "
                f"Pozīcijas: {portfolio_context.get('open_positions', 'Nav')}, Stāvoklis: {portfolio_context.get('health_state', 'NORMAL')}"
            )
        if universe_context:
            context_parts.append(f"Aktīvu pārklājums: {universe_context}")
        if obsidian_context:
            context_parts.append(f"Obsidian & Git statuss: {obsidian_context}")
        if radar_context:
            top_r = ", ".join(f"{op.get('ticker')}({op.get('grade')})" for op in radar_context[:4])
            context_parts.append(f"Top radara aktīvi: {top_r}")
        if trade_history_context:
            context_parts.append(f"Pēdējie darījumi: {trade_history_context.strip()}")
        if recent_lessons:
            context_parts.append(f"Autopsijas mācības: {'; '.join(recent_lessons[:2])}")
        if log_context:
            context_parts.append(f"Žurnāls / Veto: {log_context.strip()[:300]}")

        joined_context = "\n".join(f"• {p}" for p in context_parts)

        sys_prompt = (
            "Tu esi KODA — institucionāla līmeņa kvantitatīvais tirdzniecības partneris un AI asistents. "
            "Atbildi tekošā, profesionālā un dabiskā latviešu valodā.\n\n"
            "SVARĪGĀKIE NOTEIKUMI:\n"
            "1. KONSĪZUMS UN TIEŠUMS: Sniedz īsu, konkrētu un trāpīgu atbildi (Maksimums 3-4 teikumi). "
            "Nekad neatkārto frāzes, nelieto tukšus ievadvārdus un neģenerē bezgalīgus sarakstus!\n"
            "2. STATUSS & OBSIDIAN: Ja vaicā par statusu vai Obsidian, īsi norādi pašreizējo stāvokli (aktīvs, režīms, Git sinhronizācija ar nicispro/tbot), balstoties uz sniegtajiem faktiem.\n"
            "3. JĒDZIENI: Ja jautā par indikatoriem/jēdzieniem (RSI, ATR, SMA, režīmiem), īsi un skaidri paskaidro to būtību ar 1 teikuma piemēru.\n"
            "4. FORMATĒJUMS: Izmanto Telegram HTML tagus (<b>treknraksts</b>, <code>kods</code>). Nelieto markdown '**'."
        )

        user_content = f"""SISTĒMAS REĀLLAIKA KONTEKSTS:
{joined_context}

LIETOTĀJA JAUTĀJUMS:
{question}

Sniedz īsu, skaidru un profesionālu atbildi latviešu valodā (maksimums 3-4 teikumi):"""

        messages = [
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": user_content}
        ]

        llm_response = self.generate_chat_response(messages=messages, temperature=0.3, max_tokens=300)
        if not llm_response.startswith("⚠️ Groq AI models currently unavailable") and not llm_response.startswith("🤖 Groq Cloud AI API key is not configured"):
            return llm_response

        # Dynamic fallback if all LLM candidates fail (e.g. rate limits or offline)
        stock_free = portfolio_context.get('stock_free', 0.0) if portfolio_context else 0.0
        crypto_free = portfolio_context.get('crypto_free', 0.0) if portfolio_context else 0.0
        health = portfolio_context.get('health_state', 'NORMAL') if portfolio_context else 'NORMAL'
        open_pos = portfolio_context.get('open_positions', 'Nav') if portfolio_context else 'Nav'

        q_lower = question.lower().strip()

        # 1. Casual greetings fallback
        if any(q_lower == g or q_lower.startswith(g + " ") for g in ("cau", "čau", "sveiks", "sveiki", "kā iet", "ka iet", "kā klājas", "ka klajas", "labrīt", "labdien", "labvakar", "hello", "hi")):
            regime_simple = regime_context.split(" ")[0] if regime_context else "BULL"
            return format_for_telegram_html(
                f"👋 <b>Čau! Sistēma darbojas stabili un ir pilnā gatavībā.</b>\n\n"
                f"Tirgus režīms: <code>{regime_simple}</code>. Risku kontrole un skeneri aktīvi uzrauga jaunas iespējas. Kā varu palīdzēt?"
            )

        # 2. Obsidian question fallback
        if "obsidian" in q_lower:
            if obsidian_context:
                return format_for_telegram_html(
                    f"📓 <b>Obsidian Vault & Git Sinhronizācijas Statuss</b>\n\n"
                    f"• {obsidian_context}\n\n"
                    f"💡 <i>Visi darījumi, autopsijas un analīzes piezīmes tiek automātiski saglabātas un sinhronizētas ar Git.</i>"
                )
            return format_for_telegram_html(
                "📓 <b>Obsidian Eksportētājs ir aktīvs.</b>\n\nMape: <code>/opt/koda_bot/obsidian_vault</code> ar automātisku Git sinhronizāciju."
            )

        # 3. Error/Logs/Veto fallback
        if any(k in q_lower for k in ("kļūd", "klud", "error", "issue", "log", "problēm", "veto", "noraid")):
            if log_context and log_context.strip() and "No active error traces" not in log_context:
                return format_for_telegram_html(
                    f"🔍 <b>Sistēmas Žurnāla un Veto Analīze:</b>\n\n"
                    f"{log_context}\n\n"
                    f"💡 <i>Visi veto filtri darbojas preventīvi, lai aizsargātu kapitālu no statistiski nelabvēlīgiem darījumiem.</i>"
                )
            return format_for_telegram_html(
                f"🟢 <b>Sistēmas veselība ir teicama.</b>\n\n"
                f"Stāvoklis: <code>{health}</code>. Aktīvu kļūdu vai avārijas signālu žurnālā nav reģistrēts."
            )

        # 4. Concept questions fallback
        if "trending_bull" in q_lower or "bull" in q_lower:
            return format_for_telegram_html(
                "📈 <b>Kas ir TRENDING_BULL režīms?</b>\n\n"
                "Tas ir tirgus stāvoklis, kad galvenie etaloni (piem., S&P 500, BTC) atrodas stabilā augšupejošā trendā virs saviem 50 dienu mainīgajiem vidējiem (SMA) un volatilitāte ir kontrolēta.\n\n"
                "• <b>Taktika:</b> Prioritāte ir trenda sekotāju (*momentum*) un atsitiena (*pullback*) pirkšanas stratēģijām ar paaugstinātu riska toleranci."
            )

        # 5. General overview fallback
        fallback_summary = (
            f"📊 <b>KODA Sistēmas Pārskats</b>\n\n"
            f"• <b>Tirgus Režīms:</b> <code>{regime_context or 'NORMAL'}</code>\n"
            f"• <b>Kapitāls:</b> Akcijas: <code>${stock_free:,.2f}</code> | Kripto: <code>{crypto_free:,.2f} USDT</code>\n"
            f"• <b>Atvērtās Pozīcijas:</b> <code>{open_pos}</code>\n"
            f"• <b>Riska Stāvoklis:</b> <code>{health}</code>\n"
        )
        if radar_context:
            top_t = radar_context[0].get("ticker", "N/A")
            top_sc = radar_context[0].get("composite_score", 0.0)
            fallback_summary += f"• <b>Galvenā Iespēja:</b> <code>{top_t}</code> (Vērtējums: <b>{top_sc:.0f}</b>/100)\n"

        return format_for_telegram_html(fallback_summary)


# Aliases for backward compatibility and provider abstraction
AIAnalyzerClient = GroqClient
OpenRouterClient = GroqClient
